### PR TITLE
Use updated ts export default from i18next

### PR DESCRIPTION
**Pull request by rosskevin**
Depends on release of i18next/i18next#1352

### CODE REVIEW

**Comment by jamuhl** [comment]
tests fail on travis...not sure why.

**Comment by jamuhl** [comment]
circle ci fails also: https://circleci.com/gh/i18next/i18next-xhr-backend/5

**Comment by jamuhl** [comment]
also fails locally

**Comment by jamuhl** [comment]
hope I sorted it out: https://github.com/i18next/i18next-xhr-backend/commit/43ac1382a86ca4aac6cc5faef06cef74ca7404cd

published in i18next-xhr-backend@3.2.1

**Comment by rosskevin** [comment]
Thanks @jamuhl, I see you pushed a fix.

**Pull request merged**
