### PR TITLE
Fix the types and use exposed types from i18next

### PR DESCRIPTION
**Pull request by rosskevin**
- [x] Depends on PR https://github.com/i18next/i18next/pull/1296

### CODE REVIEW

**Comment by rosskevin** [comment]
I've got local changes ready to go, waiting on the upstream PR to be merged so we can get a green build again.

**Comment by rosskevin** [comment]
Still needs some updates to usage of internal services.  https://github.com/i18next/i18next/pull/1297#issuecomment-517696046

I have pushed all my local changes.

**Comment by jamuhl** [comment]
published in i18next-xhr-backend@3.0.1

**Comment by Kamahl19** [comment]
I have updated to i18next 17.0.8 & i18next-xhr-backend 3.0.1 but I am still getting an error
```
Argument of type 'typeof I18NextXhrBackend' is not assignable to parameter of type 'Module | ThirdPartyModule[]'.
  Type 'typeof I18NextXhrBackend' is missing the following properties from type 'ThirdPartyModule[]': pop, push, concat, join, and 27 more.  TS2345
```

**Comment by caroe233** [comment]
> I have updated to i18next 17.0.8 & i18next-xhr-backend 3.0.1 but I am still getting an error
> 
> ```
> Argument of type 'typeof I18NextXhrBackend' is not assignable to parameter of type 'Module | ThirdPartyModule[]'.
>   Type 'typeof I18NextXhrBackend' is missing the following properties from type 'ThirdPartyModule[]': pop, push, concat, join, and 27 more.  TS2345
> ```

Me too :(

It seems in the change the XHR Backend is typed as BackendModule but the i18next change expects a Module ... ?

**Pull request merged**
