### PR TITLE
Add types

### PR DESCRIPTION
**Pull request by VincentLanglet**
CF : https://github.com/i18next/i18next-xhr-backend/issues/295
Types are mainly from DefinitivelyTyped (first commit)

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@rosskevin I think it's ok now

**Comment by VincentLanglet** [comment]
@jamuhl It's a patch release

**Comment by VincentLanglet** [comment]
@rosskevin Thanks !

If you have time, I did the same for
https://github.com/i18next/i18next-browser-languageDetector
https://github.com/i18next/i18next-chained-backend
https://github.com/i18next/i18next-localstorage-backend

**Comment by jamuhl** [comment]
published in i18next-xhr-backend@2.0.0

**Pull request merged**
