### PR TITLE
Bundle all entry points with rollup

### PR DESCRIPTION
**Pull request by TrySound**
Similar to https://github.com/i18next/i18next-chained-backend/pull/8

Why do you still support bower?

### CODE REVIEW

**Comment by jamuhl** [comment]
removing bower...was something i missed the last few publishes

**Comment by TrySound** [comment]
I can send PRs if you want :)

**Comment by jamuhl** [comment]
no need for extra PR...

**Comment by jamuhl** [comment]
published in i18next-xhr-backend@3.0.0

thanks again

**Comment by TrySound** [comment]
Do you need committed umd files without bower?

**Comment by jamuhl** [comment]
not 100% sure...are there as a place for the stoneage users using jquery and manual script copying...

not sure but i think CDN.js pulls them too (but not sure - think in the past it was like that)

**Comment by jamuhl** [comment]
might sound weird...but most of this repos exist for rather long...pre "modern" web

**Comment by TrySound** [comment]
Such bundles can be easily consumed with unpkg. You may just add links to readme instead of committing files.
https://unpkg.com/i18next-chained-backend@2.0.0/dist/umd/

**Comment by jamuhl** [comment]
I know they can be consumed by unpkg - do all others?

**Comment by jamuhl** [comment]
but agree...could be removed with that note at some point

**Pull request merged**
