### PR TITLE
Fix mistake with requireJS variable definition

### PR DESCRIPTION
**Pull request by JaTochNietDan**
There seems to have been a mistake with how the requireJS stuff was initialised in your latest release. I have fixed it now and it seems to be working well.

### CODE REVIEW

**Comment by jamuhl** [comment]
define on window...don't get it

**Comment by JaTochNietDan** [comment]
My mistake, you are right. I will investigate further.

**Comment by jamuhl** [comment]
it's just a named define: http://requirejs.org/docs/api.html#modulename

**Comment by JaTochNietDan** [comment]
We're having an issue with naming it when importing it that wasn't there previously. We import it and name it as `i18nextXHR` however when we run `console.log 'i18next:', i18nextXHR` we get undefined.

This wasn't an issue back in 0.3.0.

**Comment by jamuhl** [comment]
we changed the build process to rollup...reduced the size of output massively. but from that point the export (define) is named.

**Comment by JaTochNietDan** [comment]
Ah I understand the problem now, I didn't realise require would need the configuration name to be the same once you've switched to a named module.

My mistake, thanks for the information :+1:.

**Comment by jamuhl** [comment]
perfect...

**Pull request closed without merging**
