### PR TITLE
typings for typeScript projects

### PR DESCRIPTION
**Pull request by andrewMuntyan**
Hi, @jamuhl!

First of all i would say that this plugin is very useful. Tnx for it!
But recently i have started to use your 18next-xhr-beckend plugin for i18next in some typescript project. And during typescript compilation process i have seen such error:
```javascript
"/yourHost/pathToApp/pathToFile/filename.ts(3,26): Cannot find module 'i18next-xhr-backend'."
```

So, I would suggest a little fix for this issue. But can You check my *.d.ts file? May i miss something?

### CODE REVIEW

**Comment by jamuhl** [comment]
personally don't care for typescript at all...but merged

**Comment by andrewMuntyan** [comment]
Thanks, Jan!


-- 
ANDREW MUNTIAN
Frontend Developer
 
Cell: +380 93 604 1815 <tel:+380 93 604 1815>   Email: work.vesel4ak@gmail.com <mailto:work.vesel4ak@gmail.com>   Skype: vessel4ak <tel:+380 93 604 1815>
Lviv, Ukraine

**Comment by jamuhl** [comment]
just found https://github.com/DefinitelyTyped/DefinitelyTyped might be a better place for that typescript stuff...definition for the xhr-backend is there already...

as result i consider removing the `typings` folder again - as that won't be maintained

**Comment by andrewMuntyan** [comment]
> https://github.com/DefinitelyTyped/DefinitelyTyped might be a better place for that typescript stuff...

yeah, i agree. I should make PR to that repo.

BTW, where did You find 
>definition for the xhr-backend

?
i see only i18next-node-fs-backend typings there.

**Comment by jamuhl** [comment]
right...my eye cheated me ;)

**Comment by jamuhl** [comment]
just let me know if we can remove it...thanks a lot

**Comment by andrewMuntyan** [comment]
> just let me know if we can remove it...

sure
i'll do PR to typing as soon as I get a little free time

**Pull request merged**
