### PR TITLE
BUG: Attempt to concat string from object

### PR DESCRIPTION
**Pull request by chrish619**
* Attempt to concat url from `data` object, instead of `url`
* Only need to apply `_t` to query string if request is "GET"
  * In previous code, a GET would never have the `_t` query string appended

### CODE REVIEW

**Comment by jamuhl** [comment]
GET request should not have _t applied...would result in disabling cache - not really what you want.

**Comment by chrish619** [comment]
From what I read of the original code:
```
if (!cache) { ...
```
The intention is to disable cache, when avoiding cache.

**Comment by jamuhl** [comment]
argh...just testing...pulled the last PR without checking to deep - but obviously messed up a lot. Looking deeper i think cache was appended wrong before already...should not be added to post - will result in wrong data added on send missing...

**Comment by jamuhl** [comment]
pulished in i18next-xhr-backend@1.4.1

thanks for clearing that out

**Pull request merged**
